use std::io::{Read, Write};

use base64::prelude::{BASE64_STANDARD, Engine as _};
use base64::{read::DecoderReader, write::EncoderWriter};

use super::traits::{
    self, DecodeBase64, DecodeBase64Stream, EncodeBase64, EncodeBase64Stream, Error,
};

impl EncodeBase64 for &[u8] {
    fn encode_base64(&self) -> String {
        BASE64_STANDARD.encode(self)
    }
}

impl<const N: usize> EncodeBase64 for &[u8; N] {
    fn encode_base64(&self) -> String {
        self.as_slice().encode_base64()
    }
}

impl EncodeBase64 for Vec<u8> {
    fn encode_base64(&self) -> String {
        self.as_slice().encode_base64()
    }
}

impl DecodeBase64 for &str {
    fn decode_base64(&self) -> traits::Result<Vec<u8>> {
        match BASE64_STANDARD.decode(self) {
            Ok(bytes) => Ok(bytes),
            Err(reason) => Err(Error::Base64Decode(reason.to_string())),
        }
    }
}

impl DecodeBase64 for String {
    fn decode_base64(&self) -> traits::Result<Vec<u8>> {
        self.as_str().decode_base64()
    }
}

impl<R: Read> EncodeBase64Stream for R {
    fn encode_base64_stream<W: Write>(&mut self, writer: &mut W) -> traits::Result<()> {
        let mut encoder = EncoderWriter::new(writer, &BASE64_STANDARD);

        std::io::copy(self, &mut encoder)
            .map_err(|reason| Error::Base64StreamEncode(reason.to_string()))?;

        // Flush padding.
        encoder
            .finish()
            .map_err(|reason| Error::Base64StreamEncode(reason.to_string()))?;

        Ok(())
    }
}

impl<R: Read> DecodeBase64Stream for R {
    fn decode_base64_stream<W: Write>(&mut self, writer: &mut W) -> traits::Result<()> {
        let mut decoder = DecoderReader::new(self, &BASE64_STANDARD);

        std::io::copy(&mut decoder, writer)
            .map_err(|reason| Error::Base64StreamDecode(reason.to_string()))?;

        Ok(())
    }
}

#[cfg(test)]
pub mod tests {
    use std::io::Cursor;

    use super::*;

    const HELLO_WORLD_1000: &str = "aGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIWhlbGxvLCB3b3JsZCFoZWxsbywgd29ybGQhaGVsbG8sIHdvcmxkIQ==";

    #[test]
    fn base64_encode_bytes() {
        let plaintext = b"hello, world!";

        let base64 = plaintext.encode_base64();

        assert_eq!(base64, "aGVsbG8sIHdvcmxkIQ==");
    }

    #[test]
    fn base64_decode_string() {
        let base64 = "aGVsbG8sIHdvcmxkIQ==";

        let plaintext = base64.decode_base64().unwrap();
        let plaintext = String::from_utf8_lossy(&plaintext).to_string();

        assert_eq!(plaintext, "hello, world!");
    }

    #[test]
    fn base64_encode_bytes_stream_short() {
        let plaintext = b"hello, world!";

        let mut buf = Vec::new();
        Cursor::new(plaintext)
            .encode_base64_stream(&mut buf)
            .unwrap();

        let base64 = String::from_utf8_lossy(&buf);

        assert_eq!(base64, "aGVsbG8sIHdvcmxkIQ==");
    }

    #[test]
    fn base64_encode_bytes_stream_long() {
        let plaintext = b"hello, world!".repeat(1000);

        let mut buf = Vec::new();
        Cursor::new(plaintext)
            .encode_base64_stream(&mut buf)
            .unwrap();

        let base64 = String::from_utf8_lossy(&buf);

        assert_eq!(base64, HELLO_WORLD_1000);
    }

    #[test]
    fn base64_decode_string_stream_short() {
        let base64 = "aGVsbG8sIHdvcmxkIQ==";

        let mut buf = Vec::new();
        Cursor::new(base64).decode_base64_stream(&mut buf).unwrap();

        let plaintext = String::from_utf8_lossy(&buf);

        assert_eq!(plaintext, "hello, world!");
    }

    #[test]
    fn base64_decode_string_stream_long() {
        let base64 = HELLO_WORLD_1000;

        let mut buf = Vec::new();
        Cursor::new(base64).decode_base64_stream(&mut buf).unwrap();

        let plaintext = String::from_utf8_lossy(&buf);

        assert_eq!(plaintext, "hello, world!".repeat(1000));
    }
}
